version: '3.1'
services:
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        ports:
            - ${PORT_MARIADB}:3306
        environment:
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - ./mariadb/data:/var/lib/mysql
        #networks:
            #customnetwork:
                #ipv4_address: 127.0.0.0
        #command: "mysqld --init-file /data/application/init.sql"

    nginx:
        working_dir: /var/www/html
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        ports:
            - ${PORT_NGINX_HTTP}:80
        links:
            - php-fpm
        volumes:
            - ${PATH_APPLICATION_ROOT}:/var/www/html
        depends_on:
            - mariadb
        #networks:
            #customnetwork:
                #ipv4_address: 127.0.0.0

    php-fpm:
        working_dir: /var/www/html
        build:
            context: ./php
            dockerfile: Dockerfile
        image: php:8.1-fpm
        container_name: php
        ports:
            - ${PORT_PHP_FPM}:9000
        environment:
            IP_HOST: ${IP_HOST}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - ${PATH_APPLICATION_ROOT}:/var/www/html
        #networks:
            #customnetwork:
                #ipv4_address: 127.0.0.0

#networks:
  #customnetwork:
    #ipam:
      #config:
        #- subnet: 127.0.0.0/16
