version: '3.3'
services:
    nginx:
        working_dir: /var/www/html
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        ports:
            - ${NGINX_PORT_HTTP}:80
        links:
            - php
        volumes:
            - ${APPLICATION_PATH}:/var/www/html
        depends_on:
            - php

    php:
        working_dir: /var/www/html
        build:
            context: ./php
            dockerfile: Dockerfile
        image: php:8.1-fpm
        container_name: php
        ports:
            - ${PHP_PORT}:9000
        environment:
            MARIADB_HOST: ${MARIADB_HOST}
            MARIADB_PORT: ${MARIADB_PORT}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        links:
            - mariadb
        volumes:
            - ${APPLICATION_PATH}:/var/www/html
        depends_on:
            - mariadb

    mariadb:
        container_name: mariadb
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        image: mariadb:latest
        ports:
            - ${MARIADB_PORT}:3306
        environment:
            MARIADB_HOST: ${MARIADB_HOST}
            MARIADB_PORT: ${MARIADB_PORT}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - ./mariadb/data:/var/lib/mysql
        #command: "mysqld --init-file /var/lib/mysql/init.sql"
