CREATE USER 'default'@'localhost' IDENTIFIED BY 'awd2@12317263nh1s2';
GRANT ALL PRIVILEGES ON *.* TO 'default'@'localhost' IDENTIFIED BY 'awd2@12317263nh1s2';
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS `database`;

CREATE DATABASE IF NOT EXISTS `database` CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`;

USE `database`;

DROP TABLE IF EXISTS `Test`;
CREATE TABLE `Test` (
	`id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
) ENGINE = 'InnoDB'
DEFAULT CHARACTER SET `utf8mb4`
DEFAULT COLLATE `utf8mb4_unicode_ci`;
